-- Ограничения

CREATE TABLE orders 
(
  ID         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY START WITH 100 INCREMENT BY 1 CONSTRAINT pk_order_id PRIMARY KEY,
  client_id  NUMBER,
  order_date DATE NOT NULL, -- ограничение на пустое поле
  order_sum  NUMBER CONSTRAINT ck_order_sum CHECK(order_sum >= 0), -- ограничение на проверку суммы > 0

-- при удалении строки из родительской таблицы – Oracle автоматически найдёт все строки ссылающиеся на эту строку в дочерней таблице и удалит их тоже
  CONSTRAINT fk_client_id FOREIGN KEY (client_id) REFERENCES clients(ID) ON DELETE CASCADE 

--В этом случае если строка родительской таблицы удаляется – Oracle найдёт все соответствующие строки в дочерней таблице и установит значение ключа в NULL.
  CONSTRAINT fk_client_id FOREIGN KEY (client_id) REFERENCES clients(ID) ON DELETE SET NULL
);

DROP TABLE orders PURGE;
DROP TABLE orders CASCADE CONSTRAINT;
ALTER TABLE orders DROP COLUMN client_id CASCADE CONSTRAINT;

INSERT INTO orders (id,client_id,order_date,order_sum) VALUES(1,1,SYSDATE,10.2);
INSERT INTO orders (client_id,order_date,order_sum) VALUES(1,SYSDATE,33);
INSERT INTO orders (client_id,order_date,order_sum) VALUES(2,SYSDATE,20.2);
INSERT INTO orders (client_id,order_date,order_sum) VALUES(3,SYSDATE,100.5);
INSERT INTO orders (client_id,order_date,order_sum) VALUES(4,SYSDATE,200.6);
INSERT INTO orders (client_id,order_date,order_sum) VALUES(5,SYSDATE,3.0);
INSERT INTO orders (client_id,order_date,order_sum) VALUES(6,SYSDATE,25.0);
INSERT INTO orders (client_id,order_date,order_sum) VALUES(6,SYSDATE,55.0);
INSERT INTO orders (client_id,order_date,order_sum) VALUES(7,SYSDATE,55.0);
